# Generated by Django 4.1.3 on 2022-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_lyric_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist'),
        ),
    ]
